# ----------------------------
# Makefile Options
# ----------------------------

NAME = head
DESCRIPTION = "The head utility for Agon"
COMPRESSED = NO
INIT_LOC = 0B0000
LDHAS_EXIT_HANDLER:=0
LDHAS_ARG_PROCESSING = 1

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
